language: ruby
rvm:
  - 2.3.0
cache: bundler
script:
  - RAILS_ENV=test bundle exec rake –trace db:migrate
  - RAILS_ENV=test bundle exec rake
notifications:
  recipients:
    - cycorld.com@gmail.com
